name: Update Lichess Tournament Ranking

on:
  schedule:
    - cron: "*/30 * * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install requests tabulate
    - name: Run script
      run: python ranking.py
